// <auto-generated />
using System;
using BTL_QlBi_a.Models.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BTL_QlBi_a.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.BanBia", b =>
                {
                    b.Property<int>("MaBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_ban");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBan"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ghi_chu");

                    b.Property<DateTime?>("GioBatDau")
                        .HasColumnType("datetime2")
                        .HasColumnName("gio_bat_dau");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hinh_anh");

                    b.Property<int?>("MaKH")
                        .HasColumnType("int")
                        .HasColumnName("ma_kh");

                    b.Property<int>("MaKhuVuc")
                        .HasColumnType("int")
                        .HasColumnName("ma_khu_vuc");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int")
                        .HasColumnName("ma_loai");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TenBan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_ban");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Trống")
                        .HasColumnName("trang_thai");

                    b.Property<decimal?>("ViTriX")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("vi_tri_x");

                    b.Property<decimal?>("ViTriY")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("vi_tri_y");

                    b.HasKey("MaBan");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaKhuVuc");

                    b.HasIndex("MaLoai");

                    b.HasIndex("TenBan")
                        .IsUnique();

                    b.ToTable("ban_bia", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.BangLuong", b =>
                {
                    b.Property<int>("MaLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_luong");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLuong"));

                    b.Property<decimal>("LuongCoBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("luong_co_ban");

                    b.Property<int>("MaNV")
                        .HasColumnType("int")
                        .HasColumnName("ma_nv");

                    b.Property<int>("Nam")
                        .HasColumnType("int")
                        .HasColumnName("nam");

                    b.Property<DateTime>("NgayTinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tinh")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("Phat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("phat");

                    b.Property<decimal>("PhuCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("phu_cap");

                    b.Property<int>("Thang")
                        .HasColumnType("int")
                        .HasColumnName("thang");

                    b.Property<decimal>("Thuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("thuong");

                    b.Property<decimal>("TongGio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tong_gio");

                    b.Property<decimal>("TongLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tong_luong");

                    b.HasKey("MaLuong");

                    b.HasIndex("MaNV");

                    b.ToTable("bang_luong", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.ChamCong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ghi_chu");

                    b.Property<DateTime?>("GioRa")
                        .HasColumnType("datetime2")
                        .HasColumnName("gio_ra");

                    b.Property<DateTime?>("GioVao")
                        .HasColumnType("datetime2")
                        .HasColumnName("gio_vao");

                    b.Property<string>("HinhAnhRa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hinh_anh_ra");

                    b.Property<string>("HinhAnhVao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hinh_anh_vao");

                    b.Property<int>("MaNV")
                        .HasColumnType("int")
                        .HasColumnName("ma_nv");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay");

                    b.Property<decimal?>("SoGioLam")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("so_gio_lam")
                        .HasComputedColumnSql("(CASE WHEN [gio_ra] IS NOT NULL THEN CAST(DATEDIFF(MINUTE, [gio_vao], [gio_ra]) AS DECIMAL(5,2)) / 60.0 ELSE 0 END)", true);

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Đúng giờ")
                        .HasColumnName("trang_thai");

                    b.Property<string>("XacThucBang")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Thủ công")
                        .HasColumnName("xac_thuc_bang");

                    b.HasKey("ID");

                    b.HasIndex("MaNV");

                    b.ToTable("cham_cong", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.ChiTietHoaDon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("MaDV")
                        .HasColumnType("int")
                        .HasColumnName("ma_dv");

                    b.Property<int?>("MaHD")
                        .HasColumnType("int")
                        .HasColumnName("ma_hd");

                    b.Property<int>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("so_luong");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(12,0)")
                        .HasColumnName("thanh_tien");

                    b.HasKey("ID");

                    b.HasIndex("MaDV");

                    b.HasIndex("MaHD");

                    b.ToTable("chi_tiet_hoa_don", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("DonGiaNhap")
                        .HasColumnType("decimal(10,0)")
                        .HasColumnName("don_gia_nhap");

                    b.Property<int>("MaHang")
                        .HasColumnType("int")
                        .HasColumnName("ma_hang");

                    b.Property<int>("MaPN")
                        .HasColumnType("int")
                        .HasColumnName("ma_pn");

                    b.Property<int>("SoLuongNhap")
                        .HasColumnType("int")
                        .HasColumnName("so_luong_nhap");

                    b.Property<decimal?>("ThanhTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(10,0)")
                        .HasColumnName("thanh_tien")
                        .HasComputedColumnSql("[so_luong_nhap] * [don_gia_nhap]", true);

                    b.HasKey("ID");

                    b.HasIndex("MaHang");

                    b.HasIndex("MaPN");

                    b.ToTable("chi_tiet_phieu_nhap", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.ChucNang", b =>
                {
                    b.Property<string>("MaCN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_cn");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TenCN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_cn");

                    b.HasKey("MaCN");

                    b.ToTable("chuc_nang", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.DatBan", b =>
                {
                    b.Property<int>("MaDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_dat");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDat"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghi_chu");

                    b.Property<int?>("MaBan")
                        .HasColumnType("int")
                        .HasColumnName("ma_ban");

                    b.Property<int?>("MaKH")
                        .HasColumnType("int")
                        .HasColumnName("ma_kh");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("sdt");

                    b.Property<int?>("SoNguoi")
                        .HasColumnType("int")
                        .HasColumnName("so_nguoi");

                    b.Property<string>("TenKhach")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_khach");

                    b.Property<DateTime>("ThoiGianDat")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_gian_dat");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Đang chờ")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaDat");

                    b.HasIndex("MaBan");

                    b.HasIndex("MaKH");

                    b.ToTable("dat_ban", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.DichVu", b =>
                {
                    b.Property<int>("MaDV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_dv");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDV"));

                    b.Property<string>("DonVi")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("phần")
                        .HasColumnName("don_vi");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(10,0)")
                        .HasColumnName("gia");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hinh_anh");

                    b.Property<string>("Loai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Khác")
                        .HasColumnName("loai");

                    b.Property<int?>("MaHang")
                        .HasColumnType("int")
                        .HasColumnName("ma_hang");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mo_ta");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TenDV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_dv");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Còn hàng")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaDV");

                    b.HasIndex("MaHang");

                    b.ToTable("dich_vu", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.GiaGioChoi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("ApDungTuNgay")
                        .HasColumnType("datetime2")
                        .HasColumnName("ap_dung_tu_ngay");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(10,0)")
                        .HasColumnName("gia");

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time")
                        .HasColumnName("gio_bat_dau");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time")
                        .HasColumnName("gio_ket_thuc");

                    b.Property<string>("KhungGio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("khung_gio");

                    b.Property<int?>("MaLoai")
                        .HasColumnType("int")
                        .HasColumnName("ma_loai");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Đang áp dụng")
                        .HasColumnName("trang_thai");

                    b.HasKey("ID");

                    b.HasIndex("MaLoai");

                    b.ToTable("gia_gio_choi", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.HoaDon", b =>
                {
                    b.Property<int>("MaHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_hd");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHD"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghi_chu");

                    b.Property<string>("GhiChuGiamGia")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ghi_chu_giam_gia");

                    b.Property<decimal>("GiamGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("giam_gia");

                    b.Property<int?>("MaBan")
                        .HasColumnType("int")
                        .HasColumnName("ma_ban");

                    b.Property<string>("MaGiaoDichQR")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ma_giao_dich_qr");

                    b.Property<int?>("MaKH")
                        .HasColumnType("int")
                        .HasColumnName("ma_kh");

                    b.Property<int?>("MaNV")
                        .HasColumnType("int")
                        .HasColumnName("ma_nv");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Tiền mặt")
                        .HasColumnName("phuong_thuc_thanh_toan");

                    b.Property<string>("QRCodeUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("qr_code_url");

                    b.Property<DateTime?>("ThoiGianBatDau")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_gian_bat_dau");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_gian_ket_thuc");

                    b.Property<int?>("ThoiLuongPhut")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasColumnName("thoi_luong_phut")
                        .HasComputedColumnSql("(CASE WHEN [thoi_gian_ket_thuc] IS NOT NULL THEN DATEDIFF(MINUTE, [thoi_gian_bat_dau], [thoi_gian_ket_thuc]) ELSE 0 END)", true);

                    b.Property<decimal>("TienBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tien_ban");

                    b.Property<decimal>("TienDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tien_dich_vu");

                    b.Property<decimal>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tong_tien");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Đang chơi")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaHD");

                    b.HasIndex("MaBan");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaNV");

                    b.ToTable("hoa_don", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.KhachHang", b =>
                {
                    b.Property<int>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_kh");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKH"));

                    b.Property<int>("DiemTichLuy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("diem_tich_luy");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("HangTV")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Đồng")
                        .HasColumnName("hang_tv");

                    b.Property<bool>("HoatDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("hoat_dong");

                    b.Property<DateTime?>("LanDenCuoi")
                        .HasColumnType("datetime2")
                        .HasColumnName("lan_den_cuoi");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mat_khau");

                    b.Property<DateTime>("NgayDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_dang_ky")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_sinh");

                    b.Property<string>("SDT")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("sdt");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_kh");

                    b.Property<decimal>("TongChiTieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tong_chi_tieu");

                    b.HasKey("MaKH");

                    b.HasIndex("SDT")
                        .IsUnique()
                        .HasFilter("[sdt] IS NOT NULL");

                    b.ToTable("khach_hang", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.KhuVuc", b =>
                {
                    b.Property<int>("MaKhuVuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_khu_vuc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhuVuc"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TenKhuVuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_khu_vuc");

                    b.HasKey("MaKhuVuc");

                    b.HasIndex("TenKhuVuc")
                        .IsUnique();

                    b.ToTable("khu_vuc", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.LichSuHoatDong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ChiTiet")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("chi_tiet");

                    b.Property<string>("HanhDong")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hanh_dong");

                    b.Property<int?>("MaNV")
                        .HasColumnType("int")
                        .HasColumnName("ma_nv");

                    b.Property<DateTime>("ThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_gian")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("ID");

                    b.HasIndex("MaNV");

                    b.ToTable("lich_su_hoat_dong", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.LoaiBan", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_loai");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<decimal>("GiaGio")
                        .HasColumnType("decimal(10,0)")
                        .HasColumnName("gia_gio");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_loai");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Đang áp dụng")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaLoai");

                    b.HasIndex("TenLoai")
                        .IsUnique();

                    b.ToTable("loai_ban", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.MatHang", b =>
                {
                    b.Property<int>("MaHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_hang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHang"));

                    b.Property<string>("DonVi")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("cái")
                        .HasColumnName("don_vi");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(10,0)")
                        .HasColumnName("gia");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hinh_anh");

                    b.Property<string>("Loai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Khác")
                        .HasColumnName("loai");

                    b.Property<int?>("MaNCCDefault")
                        .HasColumnType("int")
                        .HasColumnName("ma_ncc_default");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mo_ta");

                    b.Property<DateTime?>("NgayNhapGanNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_nhap_gan_nhat");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("NguongCanhBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10)
                        .HasColumnName("nguong_canh_bao");

                    b.Property<int>("SoLuongTon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("so_luong_ton");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_hang");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Còn hàng")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaHang");

                    b.HasIndex("MaNCCDefault");

                    b.ToTable("mat_hang", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.NhaCungCap", b =>
                {
                    b.Property<int>("MaNCC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_ncc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNCC"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("SDT")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("sdt");

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_ncc");

                    b.HasKey("MaNCC");

                    b.ToTable("nha_cung_cap", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.NhanVien", b =>
                {
                    b.Property<int>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_nv");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNV"));

                    b.Property<string>("CaMacDinh")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("Sáng")
                        .HasColumnName("ca_mac_dinh");

                    b.Property<string>("FaceIDAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("faceid_anh");

                    b.Property<string>("FaceIDHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("faceid_hash");

                    b.Property<decimal>("LuongCoBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("luong_co_ban");

                    b.Property<int>("MaNhom")
                        .HasColumnType("int")
                        .HasColumnName("ma_nhom");

                    b.Property<string>("MaVanTay")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_van_tay");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mat_khau");

                    b.Property<decimal>("PhuCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("phu_cap");

                    b.Property<string>("SDT")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("sdt");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_nv");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Đang làm")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaNV");

                    b.HasIndex("FaceIDHash")
                        .IsUnique()
                        .HasFilter("[faceid_hash] IS NOT NULL");

                    b.HasIndex("MaNhom");

                    b.HasIndex("MaVanTay")
                        .IsUnique()
                        .HasFilter("[ma_van_tay] IS NOT NULL");

                    b.ToTable("nhan_vien", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.NhomQuyen", b =>
                {
                    b.Property<int>("MaNhom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_nhom");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhom"));

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_nhom");

                    b.HasKey("MaNhom");

                    b.HasIndex("TenNhom")
                        .IsUnique();

                    b.ToTable("nhom_quyen", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.PhanQuyen", b =>
                {
                    b.Property<int>("MaNhom")
                        .HasColumnType("int")
                        .HasColumnName("ma_nhom");

                    b.Property<string>("MaCN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_cn");

                    b.HasKey("MaNhom", "MaCN");

                    b.HasIndex("MaCN");

                    b.ToTable("phan_quyen", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.PhieuNhap", b =>
                {
                    b.Property<int>("MaPN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_pn");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPN"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ghi_chu");

                    b.Property<int>("MaNCC")
                        .HasColumnType("int")
                        .HasColumnName("ma_ncc");

                    b.Property<int>("MaNV")
                        .HasColumnType("int")
                        .HasColumnName("ma_nv");

                    b.Property<DateTime>("NgayNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_nhap")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tong_tien");

                    b.HasKey("MaPN");

                    b.HasIndex("MaNCC");

                    b.HasIndex("MaNV");

                    b.ToTable("phieu_nhap", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.SoQuy", b =>
                {
                    b.Property<int>("MaPhieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_phieu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieu"));

                    b.Property<string>("LoaiPhieu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("loai_phieu");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ly_do");

                    b.Property<int?>("MaHDLienQuan")
                        .HasColumnType("int")
                        .HasColumnName("ma_hd_lien_quan");

                    b.Property<int>("MaNV")
                        .HasColumnType("int")
                        .HasColumnName("ma_nv");

                    b.Property<DateTime>("NgayLap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_lap")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(12,0)")
                        .HasColumnName("so_tien");

                    b.HasKey("MaPhieu");

                    b.HasIndex("MaHDLienQuan");

                    b.HasIndex("MaNV");

                    b.ToTable("so_quy", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.BanBia", b =>
                {
                    b.HasOne("BTL_QlBi_a.Models.Entities.KhachHang", "KhachHang")
                        .WithMany("BanBias")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BTL_QlBi_a.Models.Entities.KhuVuc", "KhuVuc")
                        .WithMany("BanBias")
                        .HasForeignKey("MaKhuVuc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BTL_QlBi_a.Models.Entities.LoaiBan", "LoaiBan")
                        .WithMany("BanBias")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("KhuVuc");

                    b.Navigation("LoaiBan");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.BangLuong", b =>
                {
                    b.HasOne("BTL_QlBi_a.Models.Entities.NhanVien", "NhanVien")
                        .WithMany("BangLuongs")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.ChamCong", b =>
                {
                    b.HasOne("BTL_QlBi_a.Models.Entities.NhanVien", "NhanVien")
                        .WithMany("ChamCongs")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.ChiTietHoaDon", b =>
                {
                    b.HasOne("BTL_QlBi_a.Models.Entities.DichVu", "DichVu")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaDV")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BTL_QlBi_a.Models.Entities.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHD")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DichVu");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("BTL_QlBi_a.Models.Entities.MatHang", "MatHang")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BTL_QlBi_a.Models.Entities.PhieuNhap", "PhieuNhap")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaPN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatHang");

                    b.Navigation("PhieuNhap");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.DatBan", b =>
                {
                    b.HasOne("BTL_QlBi_a.Models.Entities.BanBia", "BanBia")
                        .WithMany("DatBans")
                        .HasForeignKey("MaBan")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BTL_QlBi_a.Models.Entities.KhachHang", "KhachHang")
                        .WithMany("DatBans")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BanBia");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.DichVu", b =>
                {
                    b.HasOne("BTL_QlBi_a.Models.Entities.MatHang", "MatHang")
                        .WithMany("DichVus")
                        .HasForeignKey("MaHang")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MatHang");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.GiaGioChoi", b =>
                {
                    b.HasOne("BTL_QlBi_a.Models.Entities.LoaiBan", "LoaiBan")
                        .WithMany("GiaGioChois")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LoaiBan");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.HoaDon", b =>
                {
                    b.HasOne("BTL_QlBi_a.Models.Entities.BanBia", "BanBia")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaBan")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BTL_QlBi_a.Models.Entities.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BTL_QlBi_a.Models.Entities.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BanBia");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.LichSuHoatDong", b =>
                {
                    b.HasOne("BTL_QlBi_a.Models.Entities.NhanVien", "NhanVien")
                        .WithMany("LichSuHoatDongs")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.MatHang", b =>
                {
                    b.HasOne("BTL_QlBi_a.Models.Entities.NhaCungCap", "NhaCungCap")
                        .WithMany("MatHangs")
                        .HasForeignKey("MaNCCDefault")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.NhanVien", b =>
                {
                    b.HasOne("BTL_QlBi_a.Models.Entities.NhomQuyen", "NhomQuyen")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaNhom")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhomQuyen");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.PhanQuyen", b =>
                {
                    b.HasOne("BTL_QlBi_a.Models.Entities.ChucNang", "ChucNang")
                        .WithMany("PhanQuyens")
                        .HasForeignKey("MaCN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BTL_QlBi_a.Models.Entities.NhomQuyen", "NhomQuyen")
                        .WithMany("PhanQuyens")
                        .HasForeignKey("MaNhom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucNang");

                    b.Navigation("NhomQuyen");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.PhieuNhap", b =>
                {
                    b.HasOne("BTL_QlBi_a.Models.Entities.NhaCungCap", "NhaCungCap")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("MaNCC")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BTL_QlBi_a.Models.Entities.NhanVien", "NhanVien")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhaCungCap");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.SoQuy", b =>
                {
                    b.HasOne("BTL_QlBi_a.Models.Entities.HoaDon", "HoaDon")
                        .WithMany("SoQuys")
                        .HasForeignKey("MaHDLienQuan")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BTL_QlBi_a.Models.Entities.NhanVien", "NhanVien")
                        .WithMany("SoQuys")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.BanBia", b =>
                {
                    b.Navigation("DatBans");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.ChucNang", b =>
                {
                    b.Navigation("PhanQuyens");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.DichVu", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("SoQuys");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.KhachHang", b =>
                {
                    b.Navigation("BanBias");

                    b.Navigation("DatBans");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.KhuVuc", b =>
                {
                    b.Navigation("BanBias");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.LoaiBan", b =>
                {
                    b.Navigation("BanBias");

                    b.Navigation("GiaGioChois");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.MatHang", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");

                    b.Navigation("DichVus");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.NhaCungCap", b =>
                {
                    b.Navigation("MatHangs");

                    b.Navigation("PhieuNhaps");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.NhanVien", b =>
                {
                    b.Navigation("BangLuongs");

                    b.Navigation("ChamCongs");

                    b.Navigation("HoaDons");

                    b.Navigation("LichSuHoatDongs");

                    b.Navigation("PhieuNhaps");

                    b.Navigation("SoQuys");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.NhomQuyen", b =>
                {
                    b.Navigation("NhanViens");

                    b.Navigation("PhanQuyens");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.PhieuNhap", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });
#pragma warning restore 612, 618
        }
    }
}
