// <auto-generated />
using System;
using BTL_QlBi_a.Models.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BTL_QlBi_a.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.BanBi_a", b =>
                {
                    b.Property<int>("MaBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_ban");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBan"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ghi_chu");

                    b.Property<DateTime?>("GioBatDau")
                        .HasColumnType("datetime2")
                        .HasColumnName("gio_bat_dau");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hinh_anh");

                    b.Property<string>("KhuVuc")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Tang1")
                        .HasColumnName("khu_vuc");

                    b.Property<int?>("MaKH")
                        .HasColumnType("int")
                        .HasColumnName("ma_kh");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int")
                        .HasColumnName("ma_loai");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TenBan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_ban");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Trong")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaBan");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaLoai");

                    b.HasIndex("TenBan")
                        .IsUnique();

                    b.ToTable("ban_bia", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.BangLuong", b =>
                {
                    b.Property<int>("MaLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_luong");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLuong"));

                    b.Property<decimal>("LuongCoBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("luong_co_ban");

                    b.Property<int>("MaNV")
                        .HasColumnType("int")
                        .HasColumnName("ma_nv");

                    b.Property<int>("Nam")
                        .HasColumnType("int")
                        .HasColumnName("nam");

                    b.Property<DateTime>("NgayTinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tinh")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("Phat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("phat");

                    b.Property<decimal>("PhuCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("phu_cap");

                    b.Property<int>("Thang")
                        .HasColumnType("int")
                        .HasColumnName("thang");

                    b.Property<decimal>("Thuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("thuong");

                    b.Property<decimal>("TongGio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tong_gio");

                    b.Property<decimal>("TongLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tong_luong");

                    b.HasKey("MaLuong");

                    b.HasIndex("MaNV");

                    b.ToTable("bang_luong", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.ChamCong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ghi_chu");

                    b.Property<DateTime?>("GioRa")
                        .HasColumnType("datetime2")
                        .HasColumnName("gio_ra");

                    b.Property<DateTime?>("GioVao")
                        .HasColumnType("datetime2")
                        .HasColumnName("gio_vao");

                    b.Property<string>("HinhAnhRa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hinh_anh_ra");

                    b.Property<string>("HinhAnhVao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hinh_anh_vao");

                    b.Property<int>("MaNV")
                        .HasColumnType("int")
                        .HasColumnName("ma_nv");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay");

                    b.Property<decimal?>("SoGioLam")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("so_gio_lam")
                        .HasComputedColumnSql("(CASE WHEN [gio_ra] IS NOT NULL THEN CAST(DATEDIFF(MINUTE, [gio_vao], [gio_ra]) AS DECIMAL(5,2)) / 60.0 ELSE 0 END)", true);

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("DungGio")
                        .HasColumnName("trang_thai");

                    b.Property<string>("XacThucBang")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ThuCong")
                        .HasColumnName("xac_thuc_bang");

                    b.HasKey("ID");

                    b.HasIndex("MaNV");

                    b.ToTable("cham_cong", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.ChiTietHoaDon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("MaDV")
                        .HasColumnType("int")
                        .HasColumnName("ma_dv");

                    b.Property<int?>("MaHD")
                        .HasColumnType("int")
                        .HasColumnName("ma_hd");

                    b.Property<int>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("so_luong");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(12,0)")
                        .HasColumnName("thanh_tien");

                    b.HasKey("ID");

                    b.HasIndex("MaDV");

                    b.HasIndex("MaHD");

                    b.ToTable("chi_tiet_hoa_don", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.DatBan", b =>
                {
                    b.Property<int>("MaDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_dat");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDat"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghi_chu");

                    b.Property<int?>("MaBan")
                        .HasColumnType("int")
                        .HasColumnName("ma_ban");

                    b.Property<int?>("MaKH")
                        .HasColumnType("int")
                        .HasColumnName("ma_kh");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("sdt");

                    b.Property<int?>("SoNguoi")
                        .HasColumnType("int")
                        .HasColumnName("so_nguoi");

                    b.Property<string>("TenKhach")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_khach");

                    b.Property<DateTime>("ThoiGianDat")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_gian_dat");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("DangCho")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaDat");

                    b.HasIndex("MaBan");

                    b.HasIndex("MaKH");

                    b.ToTable("dat_ban", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.DichVu", b =>
                {
                    b.Property<int>("MaDV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_dv");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDV"));

                    b.Property<string>("DonVi")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("phần")
                        .HasColumnName("don_vi");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(10,0)")
                        .HasColumnName("gia");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hinh_anh");

                    b.Property<string>("Loai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("loai");

                    b.Property<int?>("MaHang")
                        .HasColumnType("int")
                        .HasColumnName("ma_hang");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mo_ta");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("SoLuongTon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("so_luong_ton");

                    b.Property<string>("TenDV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_dv");

                    b.Property<decimal>("TiLeLoiNhuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(30.00m)
                        .HasColumnName("ti_le_loi_nhuan");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ConHang")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaDV");

                    b.HasIndex("MaHang");

                    b.ToTable("dich_vu", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.GiaGioChoi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("ApDungTuNgay")
                        .HasColumnType("datetime2")
                        .HasColumnName("ap_dung_tu_ngay");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(10,0)")
                        .HasColumnName("gia");

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time")
                        .HasColumnName("gio_bat_dau");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time")
                        .HasColumnName("gio_ket_thuc");

                    b.Property<string>("KhungGio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("khung_gio");

                    b.Property<int?>("MaLoai")
                        .HasColumnType("int")
                        .HasColumnName("ma_loai");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("DangApDung")
                        .HasColumnName("trang_thai");

                    b.HasKey("ID");

                    b.HasIndex("MaLoai");

                    b.ToTable("gia_gio_choi", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.HoaDon", b =>
                {
                    b.Property<int>("MaHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_hd");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHD"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghi_chu");

                    b.Property<decimal>("GiamGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("giam_gia");

                    b.Property<int?>("MaBan")
                        .HasColumnType("int")
                        .HasColumnName("ma_ban");

                    b.Property<int?>("MaKH")
                        .HasColumnType("int")
                        .HasColumnName("ma_kh");

                    b.Property<int?>("MaNV")
                        .HasColumnType("int")
                        .HasColumnName("ma_nv");

                    b.Property<string>("PhuongThucThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("TienMat")
                        .HasColumnName("phuong_thuc_thanh_toan");

                    b.Property<DateTime?>("ThoiGianBatDau")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_gian_bat_dau");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_gian_ket_thuc");

                    b.Property<int?>("ThoiLuongPhut")
                        .HasColumnType("int")
                        .HasColumnName("thoi_luong_phut");

                    b.Property<decimal>("TienBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tien_ban");

                    b.Property<decimal>("TienDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tien_dich_vu");

                    b.Property<decimal>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tong_tien");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("DangChoi")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaHD");

                    b.HasIndex("MaBan");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaNV");

                    b.ToTable("hoa_don", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.KhachHang", b =>
                {
                    b.Property<int>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_kh");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKH"));

                    b.Property<int>("DiemTichLuy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("diem_tich_luy");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("HangTV")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Dong")
                        .HasColumnName("hang_tv");

                    b.Property<DateTime?>("LanDenCuoi")
                        .HasColumnType("datetime2")
                        .HasColumnName("lan_den_cuoi");

                    b.Property<DateTime>("NgayDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_dang_ky")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_sinh");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("sdt");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_kh");

                    b.Property<decimal>("TongChiTieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tong_chi_tieu");

                    b.HasKey("MaKH");

                    b.HasIndex("SDT")
                        .IsUnique();

                    b.ToTable("khach_hang", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.LichSuHoatDong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ChiTiet")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("chi_tiet");

                    b.Property<string>("HanhDong")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hanh_dong");

                    b.Property<int?>("MaNV")
                        .HasColumnType("int")
                        .HasColumnName("ma_nv");

                    b.Property<DateTime>("ThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_gian")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("ID");

                    b.HasIndex("MaNV");

                    b.ToTable("lich_su_hoat_dong", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.LoaiBan", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_loai");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<decimal>("GiaGio")
                        .HasColumnType("decimal(10,0)")
                        .HasColumnName("gia_gio");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_loai");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("DangApDung")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaLoai");

                    b.HasIndex("TenLoai")
                        .IsUnique();

                    b.ToTable("loai_ban", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.MatHang", b =>
                {
                    b.Property<int>("MaHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_hang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHang"));

                    b.Property<string>("DonVi")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("cái")
                        .HasColumnName("don_vi");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(10,0)")
                        .HasColumnName("gia");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hinh_anh");

                    b.Property<string>("Loai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("loai");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mo_ta");

                    b.Property<DateTime?>("NgayNhapGanNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_nhap_gan_nhat");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NhaCungCap")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nha_cung_cap");

                    b.Property<int>("SoLuongTon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("so_luong_ton");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_hang");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ConHang")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaHang");

                    b.ToTable("mat_hang", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.NhanVien", b =>
                {
                    b.Property<int>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_nv");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNV"));

                    b.Property<string>("CaMacDinh")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("Sang")
                        .HasColumnName("ca_mac_dinh");

                    b.Property<string>("ChucVu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("chuc_vu");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FaceIDAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("faceid_anh");

                    b.Property<string>("FaceIDHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("faceid_hash");

                    b.Property<decimal>("LuongCoBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("luong_co_ban");

                    b.Property<string>("MaVanTay")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_van_tay");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mat_khau");

                    b.Property<DateTime>("NgayVaoLam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_vao_lam")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("PhuCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("phu_cap");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("sdt");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_nv");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("DangLam")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaNV");

                    b.HasIndex("FaceIDHash")
                        .IsUnique()
                        .HasFilter("[faceid_hash] IS NOT NULL");

                    b.HasIndex("MaVanTay")
                        .IsUnique()
                        .HasFilter("[ma_van_tay] IS NOT NULL");

                    b.ToTable("nhan_vien", (string)null);
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.BanBi_a", b =>
                {
                    b.HasOne("BTL_QlBi_a.Models.Entities.KhachHang", "KhachHang")
                        .WithMany("BanBias")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BTL_QlBi_a.Models.Entities.LoaiBan", "LoaiBan")
                        .WithMany("BanBi_a")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("LoaiBan");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.BangLuong", b =>
                {
                    b.HasOne("BTL_QlBi_a.Models.Entities.NhanVien", "NhanVien")
                        .WithMany("BangLuongs")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.ChamCong", b =>
                {
                    b.HasOne("BTL_QlBi_a.Models.Entities.NhanVien", "NhanVien")
                        .WithMany("ChamCongs")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.ChiTietHoaDon", b =>
                {
                    b.HasOne("BTL_QlBi_a.Models.Entities.DichVu", "DichVu")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaDV")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BTL_QlBi_a.Models.Entities.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHD")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DichVu");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.DatBan", b =>
                {
                    b.HasOne("BTL_QlBi_a.Models.Entities.BanBi_a", "BanBia")
                        .WithMany("DatBans")
                        .HasForeignKey("MaBan")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BTL_QlBi_a.Models.Entities.KhachHang", "KhachHang")
                        .WithMany("DatBans")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BanBia");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.DichVu", b =>
                {
                    b.HasOne("BTL_QlBi_a.Models.Entities.MatHang", "MatHang")
                        .WithMany("DichVus")
                        .HasForeignKey("MaHang")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MatHang");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.GiaGioChoi", b =>
                {
                    b.HasOne("BTL_QlBi_a.Models.Entities.LoaiBan", "LoaiBan")
                        .WithMany("GiaGioChois")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LoaiBan");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.HoaDon", b =>
                {
                    b.HasOne("BTL_QlBi_a.Models.Entities.BanBi_a", "BanBia")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaBan")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BTL_QlBi_a.Models.Entities.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BTL_QlBi_a.Models.Entities.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BanBia");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.LichSuHoatDong", b =>
                {
                    b.HasOne("BTL_QlBi_a.Models.Entities.NhanVien", "NhanVien")
                        .WithMany("LichSuHoatDongs")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.BanBi_a", b =>
                {
                    b.Navigation("DatBans");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.DichVu", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.KhachHang", b =>
                {
                    b.Navigation("BanBias");

                    b.Navigation("DatBans");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.LoaiBan", b =>
                {
                    b.Navigation("BanBi_a");

                    b.Navigation("GiaGioChois");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.MatHang", b =>
                {
                    b.Navigation("DichVus");
                });

            modelBuilder.Entity("BTL_QlBi_a.Models.Entities.NhanVien", b =>
                {
                    b.Navigation("BangLuongs");

                    b.Navigation("ChamCongs");

                    b.Navigation("HoaDons");

                    b.Navigation("LichSuHoatDongs");
                });
#pragma warning restore 612, 618
        }
    }
}
